FROM registry.suse.com/suse/sle15:15.3.13.18

# ADD http://rmt.test.lan/rmt.crt /etc/pki/trust/anchors/rmt.crt
# or
# COPY ./rmt.crt /etc/pki/trust/anchors/rmt.crt
#
# RUN update-ca-certificates

RUN zypper -n ref && \
  zypper -n install \
    awk \
    command-not-found \
    curl \
    hostname \
    less \
    systemd-sysvinit \
    vim \
    w3m \
    wget

# Workaround to replace rpm-ndb version from public-cloud module with default rpm
RUN zypper -n in --force-resolution rpm

COPY ./systemd-logind.service.d_override.conf /etc/systemd/system/systemd-logind.service.d/override.conf
COPY ./uptime-faker.service /etc/systemd/system/uptime-faker.service
COPY ./system-mods.service /etc/systemd/system/system-mods.service

COPY ./system-mods.sh /usr/local/sbin/system-mods.sh
COPY ./uptime.py /usr/local/sbin/uptime.py

RUN chmod +x \
  /usr/local/sbin/system-mods.sh \
  /usr/local/sbin/uptime.py

RUN systemctl enable \
  uptime-faker.service \
  system-mods.service

ENV ACTIVATION_KEY=""
ENV SUMA_HOSTNAME=""
ENV BOOTSTRAP_FILE="bootstrap-podman.sh"
ENV MIN_DELAY_SEC=0
ENV MAX_DELAY_SEC=0

CMD [ "/sbin/init" ]

